# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "pt-BR"
early_access: true
inheritance: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "**/*"
      instructions: "Atue como um especialista em Cibersegurança. Audite o código em busca de vulnerabilidades, falhas do OWASP, chaves vazadas ou permissões excessivas."
chat:
  auto_reply: true
